export type Locale = 'ko' | 'en';
export const copy = {
  ko: {
    home: '홈', review: '첨삭', resume: '이력서', career: '커리어', my: 'MY',
    greeting: '당신의 다음 챕터를 위해', hero: '경험은 당신의 것.\n전달은 더 선명하게.', heroBody: '자기소개서부터 면접 준비까지,\n한 번의 지원을 제대로 준비하세요.', start: '내 지원서 다듬기',
    tools: '어디서부터 시작할까요?', toolsSub: '지금 필요한 만큼, 한 단계씩.', quick: '문장은 명확하게', quickBody: '작성한 자소서의 표현과 흐름을 정리해요.', pro: '경험은 설득력 있게', proBody: '공고와 경험을 연결해 지원서를 보완해요.', final: '면접까지 빈틈없이', finalBody: '이력서와 자소서를 교차 확인하고 면접을 준비해요.',
    recent: '나의 지원 기록', empty: '아직 지원 기록이 없어요', emptyBody: '첫 지원서를 저장하면 여기에서 이어갈 수 있어요.', refresh: '새로고침', private: '내 자료는 나만 볼 수 있어요', privateBody: '입력한 사실을 바탕으로 정리합니다. 없는 경험이나 성과를 만들어 넣지 않습니다.',
    reviewTitle: '더 나다운 지원서', reviewBody: '먼저 지원할 곳과 원문을 알려주세요.', company: '지원 회사', role: '지원 직무', applicationTitle: '지원서 이름', question: '문항', prompt: '문항 제목 / 질문', answer: '자기소개서 원문', addQuestion: '문항 추가', remove: '삭제', target: '목표 글자 수 (선택, 100~3,000)', posting: '채용공고 원문', materials: '이력서 / 참고자료 원문', save: '비공개 저장 후 계속', import: 'TXT 파일 가져오기', textOnly: 'TXT 파일 또는 텍스트 붙여넣기를 지원합니다.', memory: '저장 전 입력은 앱 메모리에만 있습니다. 앱 종료 시 사라집니다.', market: '분석 기준', krMarket: '한국 채용 · 한국어 결과', enMarket: '미국 채용 · 영어 결과', marketPending: '영어 채용시장 분석은 준비 중입니다. 저장·결제할 수 없습니다.',
    result: '첨삭 결과', overview: '총평', questions: '문항별', revised: '수정본', interview: '면접', finalTab: 'FINAL', original: '원문', proposal: '수정 제안', reasons: '수정 이유', verify: '직접 확인할 내용', priorities: '먼저 살펴볼 3가지', copy: '복사', copied: '복사했어요', share: '공유', back: '뒤로', sample: '화면 예시 · 실제 고객 결과가 아닙니다', sampleAction: '결과 화면 미리보기', aiJudgment: 'AI의 정성적 판단 · 합격 확률이 아닙니다',
    resumeTitle: '나를 담은 한 장', resumeBody: '직접 작성한 사실로 깔끔한 이력서를 만드세요.', name: '이름', email: '이메일', headline: '직무 / 한 줄 소개', experience: '경력 · 프로젝트', education: '학력 · 교육', skills: '기술 · 자격', preview: '미리보기', pdf: 'PDF 저장 / 공유', resumeNote: '무료 직접 작성 · AI가 경력을 자동 생성하지 않습니다.', aiResumePending: 'AI 이력서 제작은 앱 결제 연동 후 제공됩니다.',
    careerTitle: '나를 이해하는 시간', careerBody: '좋아하는 일에서 다음 방향을 발견해요.', interest: '직업흥미 탐색', interestBody: '30개 활동을 통해 나의 RIASEC 흥미 경향을 살펴보세요.', careerNote: '자기 탐색용 베타 검사입니다. 능력·성격 진단이나 직무 적합성 판정이 아닙니다.', begin: '무료 검사 시작', previous: '이전', next: '다음', finish: '내 결과 보기', retake: '다시 검사', disagree: '전혀 흥미 없음', agree: '매우 흥미 있음', interestResult: '상대적으로 끌리는 활동', sameScores: '모든 영역 점수가 같습니다. 뚜렷한 선호 차이가 나타나지 않았어요.',
    login: '이메일로 로그인', loginBody: '웹에서 사용하던 계정으로 기록을 이어가세요.', sendCode: '인증번호 받기', code: '이메일 인증번호', verifyCode: '로그인', codeSent: '이메일에서 인증번호를 확인해 주세요.', signout: '로그아웃', language: '앱 언어', account: '내 계정', passes: '사용 가능한 이용권', noPasses: '사용 가능한 이용권이 없습니다.', config: '로그인 연결 설정이 필요합니다. 현재 무료 기능과 결과 예시를 사용할 수 있습니다.', loginRequired: '먼저 MY에서 로그인해 주세요. 입력 내용은 유지됩니다.', failure: '요청을 완료하지 못했어요. 연결을 확인하고 다시 시도해 주세요.', required: '지원서 이름과 답변을 입력하고 목표 글자 수를 확인해 주세요.', loading: '불러오는 중…',
    pending: '분석 준비', running: '분석 중', completed: '완료', failed: '재시도 필요', run: '이용권으로 분석 시작', retry: '추가 결제 없이 재시도', check: '진행 상태 확인', checkout: 'Google Play로 구매', restore: '미완료 구매 복구', billingPending: 'Google Play 내부 테스트 설정 후 구매할 수 있습니다.', saved: '지원서를 비공개로 저장했어요', runNotice: '분석을 시작하면 이용권이 사용됩니다. 앱을 닫아도 기록에서 이어갈 수 있습니다.', noFinal: '이 결과에는 FINAL 검수가 포함되지 않았습니다.', noInterview: '저장된 면접 질문이 없습니다.', noResume: '이력서가 제공되지 않아 서류 간 비교는 수행되지 않았습니다.',
  },
  en: {
    home: 'Home', review: 'Review', resume: 'Résumé', career: 'Career', my: 'My',
    greeting: 'FOR YOUR NEXT CHAPTER', hero: 'Your experience.\nA clearer story.', heroBody: 'From your first draft to interview preparation,\nmake every application count.', start: 'Refine my application',
    tools: 'Where shall we begin?', toolsSub: 'The right support for your next step.', quick: 'Make every sentence clear', quickBody: 'Refine the wording and flow of your draft.', pro: 'Give your experience context', proBody: 'Connect your experience to the job requirements.', final: 'Prepare for the conversation', finalBody: 'Cross-check your documents and prepare for interviews.',
    recent: 'Your applications', empty: 'A fresh start', emptyBody: 'Save your first application to pick up where you left off.', refresh: 'Refresh', private: 'Your documents stay private', privateBody: 'We work with the facts you provide. We do not invent experience or achievements.',
    reviewTitle: 'An application that sounds like you', reviewBody: 'Tell us about the role and add your draft.', company: 'Company', role: 'Role', applicationTitle: 'Application name', question: 'Question', prompt: 'Question title / prompt', answer: 'Original draft', addQuestion: 'Add a question', remove: 'Remove', target: 'Character limit (optional, 100–3,000)', posting: 'Job description', materials: 'Résumé / supporting text', save: 'Save privately and continue', import: 'Import a TXT file', textOnly: 'Paste text or import a TXT document.', memory: 'Unsaved text stays in memory and is lost when the app closes.', market: 'Review context', krMarket: 'Korean hiring · Korean output', enMarket: 'US hiring · English output', marketPending: 'English-market analysis is not yet available. Saving and purchasing are disabled.',
    result: 'Your review', overview: 'Overview', questions: 'By question', revised: 'Revision', interview: 'Interview', finalTab: 'FINAL', original: 'Original', proposal: 'Suggested revision', reasons: 'Why it changed', verify: 'Facts to verify', priorities: 'Your top priorities', copy: 'Copy', copied: 'Copied', share: 'Share', back: 'Back', sample: 'UI example · not a real customer result', sampleAction: 'Explore an example review', aiJudgment: 'Qualitative AI judgment · not a hiring probability',
    resumeTitle: 'Your story, on one page', resumeBody: 'Build a clean résumé from the facts you provide.', name: 'Name', email: 'Email', headline: 'Role / summary', experience: 'Experience · projects', education: 'Education · training', skills: 'Skills · certifications', preview: 'Preview', pdf: 'Save / share PDF', resumeNote: 'Free manual builder · no invented experience.', aiResumePending: 'AI résumé creation will follow native billing integration.',
    careerTitle: 'Make room for self-discovery', careerBody: 'Find your direction in the activities you enjoy.', interest: 'Career interests', interestBody: 'Explore your RIASEC interests through 30 activities.', careerNote: 'A beta self-exploration tool, not a diagnosis, ability test or job-fit assessment.', begin: 'Start the free assessment', previous: 'Previous', next: 'Next', finish: 'See my results', retake: 'Start again', disagree: 'Not interested', agree: 'Very interested', interestResult: 'Activities that draw your interest', sameScores: 'All areas have the same score. No distinct preference emerged.',
    login: 'Sign in with email', loginBody: 'Continue with the account you use on the web.', sendCode: 'Send a sign-in code', code: 'Email verification code', verifyCode: 'Sign in', codeSent: 'Check your email for a verification code.', signout: 'Sign out', language: 'App language', account: 'Your account', passes: 'Available passes', noPasses: 'No available passes.', config: 'Sign-in is not configured. Free tools and the example review are available.', loginRequired: 'Sign in from My first. Your draft will stay here.', failure: 'We could not complete the request. Check your connection and try again.', required: 'Enter a title and an answer, and check the character limit.', loading: 'Loading…',
    pending: 'Ready to review', running: 'Review in progress', completed: 'Complete', failed: 'Retry needed', run: 'Start with my pass', retry: 'Retry without a new purchase', check: 'Check progress', checkout: 'Purchase with Google Play', restore: 'Recover an unfinished purchase', billingPending: 'Purchases require Google Play internal testing configuration.', saved: 'Your application is saved privately', runNotice: 'Starting uses a pass. You can return to this review from your history.', noFinal: 'This review does not include FINAL checks.', noInterview: 'No interview questions were stored.', noResume: 'No résumé was supplied, so document cross-checking was not performed.',
  },
} as const;
export type Messages = { [K in keyof typeof copy.ko]: string };
