import { useState } from 'react';
import { View, Text, ScrollView, Share } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import type { ResultDocument } from '../../../src/domain/result-document';
import type { Messages } from './i18n';
import { Page, Card, Heading, Pill, Button, ui, colors } from './ui';
export function ResultScreen({ result, t, onBack, notify }: { result: ResultDocument; t: Messages; onBack: () => void; notify: (message: string) => void }) {
  const [tab, setTab] = useState('overview');
  const [questionIndex, setQuestionIndex] = useState(0);
  const question = result.questions[questionIndex];
  const copyText = async (text: string) => { try { await Clipboard.setStringAsync(text); notify(t.copied); } catch { notify(t.failure); } };
  const share = async () => { try { await Share.share({ message: `${result.isSample ? t.sample + '\n\n' : ''}${result.questions.map(q => `${q.title}\n${q.revisedAnswer}`).join('\n\n')}` }); } catch { notify(t.failure); } };
  return <View style={ui.page}><View style={{ padding: 16 }}><Button title={t.back} onPress={onBack} secondary icon="arrow-back"/></View><Page>
    {result.isSample && <Text style={[ui.muted, { color: colors.amber }]}>{t.sample}</Text>}
    <Text style={ui.eyebrow}>{result.product} / {t.result}</Text><Heading title={result.applicationLabel} subtitle={`${result.company} · ${result.role}`}/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{(['overview', 'questions', 'revised', 'interview', 'finalTab'] as const).map(id => <Pill key={id} title={t[id]} active={tab === id} onPress={() => setTab(id)}/>)}</ScrollView>
    {tab === 'overview' && <><Card style={{ backgroundColor: colors.pale }}><Text style={ui.heading}>{result.readiness.label}</Text><Text style={ui.body}>{result.readiness.summary}</Text><Text style={ui.muted}>{t.aiJudgment}</Text>{result.readiness.reasons.map((reason, i) => <Text key={i} style={ui.muted}>• {reason}</Text>)}</Card><Text style={ui.heading}>{t.priorities}</Text>{result.priorities.slice(0, 3).map((p, i) => <Card key={p.id}><Text style={ui.eyebrow}>0{i + 1}</Text><Text style={ui.heading}>{p.title}</Text><Text style={ui.body}>{p.description}</Text></Card>)}{result.coverageNotes.map((n, i) => <Text key={i} style={ui.muted}>{n}</Text>)}</>}
    {tab === 'questions' && <><ScrollView horizontal contentContainerStyle={{ gap: 8 }}>{result.questions.map((q, i) => <Pill key={q.id} title={`${i + 1}. ${q.title}`} active={questionIndex === i} onPress={() => setQuestionIndex(i)}/>)}</ScrollView><Card><Text style={ui.eyebrow}>{t.original}</Text><Text selectable style={ui.body}>{question.originalAnswer}</Text></Card><Card style={{ backgroundColor: colors.pale }}><Text style={ui.eyebrow}>{t.proposal}</Text><Text selectable style={ui.body}>{question.revisedAnswer}</Text><Button secondary title={t.copy} icon="copy-outline" onPress={() => void copyText(question.revisedAnswer)}/></Card><Card><Text style={ui.heading}>{t.reasons}</Text>{question.revisionReasons.map((r, i) => <Text key={i} style={ui.body}>• {r}</Text>)}{question.verificationNote && <Text style={[ui.body, { color: colors.amber }]}>{question.verificationNote}</Text>}</Card>{question.originalAnnotations?.map(a => <Card key={a.id}><Text style={ui.eyebrow}>{a.type.toUpperCase()}</Text><Text style={ui.body}>“{a.phrase}”</Text><Text style={ui.muted}>{a.comment}</Text>{a.suggestion && <Text style={ui.body}>{a.suggestion}</Text>}</Card>)}</>}
    {tab === 'revised' && <>{result.questions.map(q => <Card key={q.id}><Text style={ui.heading}>{q.title}</Text><Text selectable style={ui.body}>{q.revisedAnswer}</Text>{q.verificationNote && <Text style={[ui.muted, { color: colors.amber }]}>{q.verificationNote}</Text>}<Button title={t.copy} secondary icon="copy-outline" onPress={() => void copyText(q.revisedAnswer)}/></Card>)}<Button title={t.share} onPress={() => void share()} icon="share-outline"/></>}
    {tab === 'interview' && <>{!result.interviewQuestions.length && <Card><Text style={ui.body}>{t.noInterview}</Text></Card>}{result.interviewQuestions.map((q, i) => <Card key={q.id}><Text style={ui.eyebrow}>QUESTION {i + 1}</Text><Text style={ui.heading}>{q.question}</Text><Text style={ui.muted}>{q.reason}</Text>{q.answerGuide.map((g, j) => <Text key={j} style={ui.body}>• {g}</Text>)}</Card>)}</>}
    {tab === 'finalTab' && <>{result.product !== 'FINAL' ? <Card><Text style={ui.body}>{t.noFinal}</Text></Card> : <>{!result.suppliedResume && <Text style={ui.muted}>{t.noResume}</Text>}{result.documentConflicts.map(c => <Card key={c.id}><Text style={ui.heading}>{c.conflict}</Text><Text style={ui.body}>{c.resumeStatement}</Text><Text style={ui.body}>{c.coverLetterQuote}</Text><Text style={ui.muted}>{c.resolution}</Text></Card>)}{result.finalChecklist.map(c => <Card key={c.id}><Text style={ui.heading}>{c.item}</Text><Text style={ui.body}>{c.why}</Text></Card>)}{result.interviewerFlags.map(f => <Card key={f.id}><Text style={ui.heading}>{f.headline}</Text><Text style={ui.body}>{f.evidenceQuote}</Text><Text style={ui.muted}>{f.preparation}</Text></Card>)}</>}</>}
    {!!result.verificationQuestions.length && <Card><Text style={ui.heading}>{t.verify}</Text>{result.verificationQuestions.map((q, i) => <Text key={i} style={ui.body}>• {q}</Text>)}</Card>}
  </Page></View>;
}
