import { describe, expect, it } from "vitest";
import { findSpeechExpressions, locateEvidence, summarizeCamera, summarizeSpeech, trainingQuestionsRequestSchema, QUESTION_CRITERIA, DEFAULT_TRAINING_CONTEXT } from "./interview-training";
import { interviewCoachOutputSchema, validateCoachEvidence } from "./interview-feedback";
import { summarizeVisionFrames, type VisionFrame, type VisionAnalysisResult } from "@/lib/interview-media/vision-geometry";

const answer = "음... 제가 인수인계 표를 만들었습니다. 그래서 확인 항목을 공유했습니다.";
const absent = { status: "missing" as const, evidence: null, comment: "언급 없음" };
const coach = () => interviewCoachOutputSchema.parse({ summary: "결과 확인 필요", strengths: [], priorities: [], star: { situation: absent, task: absent, action: absent, result: absent }, betterAnswer: answer, verificationQuestions: [], likelyFollowups: [], unassessed: [], questionType: "experience", criteria: QUESTION_CRITERIA.experience.map(name => ({ name, ...absent })), keywords: [{ text: "인수인계 표", evidence: "인수인계 표를 만들었습니다." }], annotations: [{ quote: "확인 항목을 공유했습니다.", kind: "missing_evidence", comment: "결과 확인" }], nextTurn: { action: "follow_up", question: "공유 이후 달라진 점은 무엇인가요?", evidence: "확인 항목을 공유했습니다.", reason: "변화 확인" } });
describe("interview training evidence", () => {
  it("keeps discourse connectors separate and never counts syllables inside words", () => { const marks = findSpeechExpressions("음... 그래서 어머니와 사실상 의미를 확인했다. 약간 달랐다."); expect(marks.map(mark => mark.label)).toEqual(["음", "그래서", "약간"]); expect(marks[1].kind).toBe("linking"); });
  it("marks exact unique quotes only", () => { expect(locateEvidence("행동 했다", "행동", "강점", "strength", "근거")?.start).toBe(0); expect(locateEvidence("행동 행동", "행동", "강점", "strength", "근거")).toBeNull(); expect(locateEvidence("행동", "성과", "강점", "strength", "근거")).toBeNull(); });
  it("does not invent speech timestamps for manual answers", () => { const result = summarizeSpeech(answer, null, null); expect(result.charactersPerMinute).toBeNull(); expect(result.startDelay).toBeNull(); expect(result.segmentGaps).toEqual([]); });
  it("invalidates timestamps after transcript editing", () => { const transcription = { text: "다른 답변", segments: [{ start: 2, end: 4, text: "다른 답변" }], durationSeconds: 10, metadata: { model: "test", provider: "openai" as const, schemaVersion: "v1", requestId: crypto.randomUUID() }, notice: "" }; expect(summarizeSpeech(answer, transcription, 10).segments).toEqual([]); });
  it("supports question-specific rubric and exact keywords", () => { expect(validateCoachEvidence(answer, coach())).toEqual([]); const invalid = coach(); invalid.keywords[0].text = "불량률 50% 개선"; expect(validateCoachEvidence(answer, invalid).length).toBeGreaterThan(0); });
  it("rejects missing/duplicate/wrong-type criteria and ungrounded followups", () => { const value = coach(); value.criteria[0].name = "기업 이해"; value.nextTurn.evidence = "새 성과"; expect(validateCoachEvidence(answer, value).length).toBeGreaterThan(1); value.criteria = value.criteria.slice(0, 2); expect(validateCoachEvidence(answer, value)).toContain("평가 기준이 누락되거나 중복됐습니다."); });
  it("rejects missing consent and oversized source material", () => { const input = { requestId: crypto.randomUUID(), consent: true, company: "기업", role: "생산", count: 3, context: DEFAULT_TRAINING_CONTEXT }; expect(trainingQuestionsRequestSchema.safeParse(input).success).toBe(true); expect(trainingQuestionsRequestSchema.safeParse({ ...input, consent: false }).success).toBe(false); expect(trainingQuestionsRequestSchema.safeParse({ ...input, context: { ...input.context, supportText: "가".repeat(6001) } }).success).toBe(false); });
  it("camera denominator excludes missing frames and short samples do not get percentages", () => { const frames: VisionFrame[] = Array.from({ length: 6 }, (_, index) => ({ timeSeconds: index, status: index === 5 ? "no_face" : "single_face", landmarks: [], bounds: index === 5 ? null : { x:.4,y:.3,width:.2,height:.3 }, rollDegrees: 0 })); const result: VisionAnalysisResult = { schemaVersion:"vision-observations-v1", engine:"MediaPipe Face Landmarker / local IMAGE samples", durationSeconds:6,analyzedSeconds:6,sampleIntervalSeconds:1,width:1280,height:720,frames,summary:summarizeVisionFrames(frames),limitations:[] }; expect(summarizeCamera(result)).toMatchObject({ validSamples:5,centeredPercent:100,missingSamples:1 }); expect(summarizeCamera({ ...result,frames:frames.slice(0,3) })?.centeredPercent).toBeNull(); expect(summarizeCamera(null)).toBeNull(); });
});
