"use client";
import { useState } from "react";
import type { InterviewFeedbackResult, InterviewTranscriptionResult } from "@/domain/interview-feedback";
import { findSpeechExpressions, locateEvidence, summarizeSpeech, QUESTION_TYPES, type TextMark, type TrainingAttempt, compareAttempts, sameTrainingQuestion } from "@/domain/interview-training";
import styles from "./training-insights.module.css";

export function AnswerInsights({ answer, result, transcription, duration, onSeek, onPractice }: { answer: string; result: InterviewFeedbackResult; transcription: InterviewTranscriptionResult | null; duration: number | null; onSeek?: (seconds: number) => void; onPractice?: (question: string) => void }) {
  const [selectedMark, setSelectedMark] = useState<{ answer: string; note: string } | null>(null);
  const feedback = result.feedback;
  const speech = summarizeSpeech(answer, transcription, duration);
  const marks: TextMark[] = [...findSpeechExpressions(answer), ...feedback.strengths.flatMap(item => locateEvidence(answer, item.evidence, "좋은 표현", "strength", item.reason) ?? []), ...feedback.priorities.flatMap(item => locateEvidence(answer, item.evidence, "개선 근거", "concern", item.reason) ?? [])];
  if ("annotations" in feedback) for (const item of feedback.annotations) { const mark = locateEvidence(answer, item.quote, { strength: "좋은 표현", abstract: "추상적 표현", missing_evidence: "근거 확인", relevance: "질문 연결" }[item.kind], item.kind === "strength" ? "strength" : "concern", item.comment); if (mark) marks.push(mark); }
  const boundaries = [...new Set([0, answer.length, ...marks.flatMap(mark => [mark.start, mark.end])])].sort((a, b) => a - b);
  return <div className={styles.insights}>
    {"criteria" in feedback && <section><h3>{QUESTION_TYPES[feedback.questionType]} 답변 기준</h3><div className={styles.criteria}>{feedback.criteria.map(item => <div key={item.name}><b>{item.name}</b><span data-status={item.status}>{{ present: "근거 확인", partial: "보완 필요", missing: "언급 없음", not_applicable: "해당 없음" }[item.status]}</span><p>{item.comment}</p>{item.evidence && <q>{item.evidence}</q>}</div>)}</div></section>}
    <section><h3>내 답변에서 확인하기</h3><p className={styles.help}>원문 인용과 실제 표현만 표시합니다. 강조 부분을 누르거나 키보드로 선택하면 이유를 볼 수 있어요.</p><div className={styles.transcript}>{boundaries.slice(0, -1).map((start, index) => { const end = boundaries[index + 1]; const active = marks.filter(mark => mark.start <= start && mark.end >= end); const value = answer.slice(start, end); return active.length ? <mark key={start} role="button" tabIndex={0} onClick={() => setSelectedMark({ answer, note: active.map(mark => `${mark.label}: ${mark.note}`).join("\n") })} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelectedMark({ answer, note: active.map(mark => `${mark.label}: ${mark.note}`).join("\n") }); } }} data-kind={active.some(mark => mark.kind === "concern") ? "concern" : active[0].kind} title={active.map(mark => `${mark.label}: ${mark.note}`).join("\n")} aria-label={`${value}. ${active.map(mark => `${mark.label}: ${mark.note}`).join(". ")}`}>{value}</mark> : <span key={start}>{value}</span>; })}</div>{selectedMark?.answer === answer && <p role="status" className={styles.annotationNote}>{selectedMark.note}</p>}</section>
    {"keywords" in feedback && feedback.keywords.length > 0 && <section><h3>문장 대신 키워드로 연습</h3><div className={styles.keywords}>{feedback.keywords.map((item, index) => <span key={index} title={item.evidence}>{item.text}</span>)}</div><p className={styles.help}>이번 답변에 실제로 있는 표현입니다. 없는 경험이나 성과를 추가하지 않았는지 확인하세요.</p></section>}
    <details><summary>전달 방식 참고 · 전사 기준</summary><p className={styles.help}>{speech.caveat}</p><dl className={styles.metrics}><div><dt>경과시간 기준 글자/분</dt><dd>{speech.charactersPerMinute ?? "미측정"}</dd></div><div><dt>습관·연결 표현</dt><dd>{speech.expressions.length}회</dd></div><div><dt>연속 같은 단어</dt><dd>{speech.repeatedAdjacentWords.length}회</dd></div><div><dt>첫 전사 구간까지</dt><dd>{speech.startDelay === null ? "미측정" : `${speech.startDelay.toFixed(1)}초`}</dd></div></dl><p>‘그래서·사실·일단’은 문맥상 필요한 연결 표현일 수 있습니다. 횟수가 줄었다고 무조건 개선된 것은 아닙니다.</p>{speech.expressions.length > 0 && <p>{[...new Set(speech.expressions.map(item => item.label))].map(word => `${word} ${speech.expressions.filter(item => item.label === word).length}회`).join(" · ")}</p>}{speech.segments.length > 0 && <ul>{speech.segments.map((segment, index) => <li key={index}><button type="button" onClick={() => onSeek?.(segment.start)} disabled={!onSeek}>{segment.start.toFixed(1)}–{segment.end.toFixed(1)}초</button> {segment.charactersPerMinute ?? "—"}자/분 · {segment.text}</li>)}</ul>}{speech.segmentGaps.length > 0 && <p>전사 구간 사이 1초 이상 빈 시간 {speech.segmentGaps.length}개 · 최장 {speech.longestSegmentGap?.toFixed(1)}초 (실제 침묵 여부는 원음 확인)</p>}</details>
    {"nextTurn" in feedback && <section><h3>다음 연습</h3><p>{feedback.nextTurn.reason}</p>{feedback.nextTurn.action === "follow_up" && feedback.nextTurn.question ? <><p><b>{feedback.nextTurn.question}</b></p>{feedback.nextTurn.evidence && <q>{feedback.nextTurn.evidence}</q>}{onPractice && <button type="button" className={styles.primary} onClick={() => onPractice(feedback.nextTurn.question!)}>이 꼬리질문에 답하기</button>}</> : <p>현재 답변의 추가 확인보다 다음 주제 연습을 권합니다.</p>}</section>}
  </div>;
}

export function TrainingReport({ attempts, onPractice }: { attempts: TrainingAttempt[]; onPractice?: (question: string) => void }) {
  if (!attempts.length) return null;
  const latest = attempts.filter((item, index) => !attempts.slice(index + 1).some(next => sameTrainingQuestion(item, next)));
  const priorities = latest.flatMap(item => item.result.feedback.priorities.map(priority => ({ question: item.question, ...priority }))).slice(0, 3);
  return <section className={styles.report} aria-label="면접 훈련 기록"><h2>이번 면접의 훈련 기록</h2><p>{latest.length}개 질문 · 분석 {attempts.length}회 · 새로고침 전까지 이 탭에서만 보관</p>{priorities.length > 0 && <div className={styles.priorities}><h3>먼저 다시 연습할 답변</h3>{priorities.map((item, index) => <div key={index}><b>{item.title}</b><p>{item.reason}</p><small>{item.question}</small>{onPractice && <button type="button" onClick={() => onPractice(item.question)}>이 질문 다시 연습</button>}</div>)}<p className={styles.help}>질문별 우선 개선점을 모았습니다. 별도 AI 종합 점수나 모든 질문의 중요도 순위는 아닙니다.</p></div>}
    {latest.map(item => { const history = attempts.filter(attempt => sameTrainingQuestion(item, attempt)); const before = history.length > 1 ? history[0] : null; const comparison = before ? compareAttempts(before, item) : null; return <details key={item.id}><summary>{item.question} · {history.length}차</summary><p>{item.result.feedback.summary}</p><h4>이번 답변</h4><p className={styles.transcript}>{item.answer}</p>{comparison && before && <><h4>첫 답변 → 이번 답변</h4><dl className={styles.metrics}>{[["답변시간(초)", comparison.duration], ["전사 표현 횟수", comparison.expressions], ["STAR 근거 확인(4항목)", comparison.star], ["공백 제외 글자", comparison.chars]].map(([name, values]) => <div key={String(name)}><dt>{String(name)}</dt><dd>{(values as (number | null)[]).map(value => value ?? "미측정").join(" → ")}</dd></div>)}</dl><p className={styles.help}>동일 질문·기업·직무·평가 버전만 비교합니다. 줄어든 시간/표현 수가 반드시 개선을 뜻하지 않으며 STAR가 적합하지 않은 질문은 해당 항목을 참고하지 마세요.</p><h4>첫 답변</h4><p className={styles.transcript}>{before.answer}</p></>}{before && !comparison && <p>평가 버전이 달라 수치 비교를 생략했습니다.</p>}<h4>이번 답변에서 보완할 점</h4>{item.result.feedback.priorities.map((priority, index) => <p key={index}><b>{priority.title}</b> — {priority.practice}</p>)}{onPractice && <button type="button" onClick={() => onPractice(item.question)}>이 질문 다시 연습하기</button>}</details>; })}
  </section>;
}
