"use client";
import Link from "next/link";
import { useEffect, useMemo, useState, useSyncExternalStore } from "react";
import { ArrowRight, CheckCircle2, Sparkles, WandSparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import styles from "./career-ai-preparation.module.css";
const subscribe=()=>()=>undefined;
const assessments=[{key:"interest",label:"직업흥미 탐색",href:"/career/interest",storage:"mooa-career-interest-answers-v1",hint:"무엇을 해 보고 싶은가"},{key:"work_style",label:"업무성향 분석",href:"/career/work-style",storage:"mooa-work-style-answers-v1",hint:"어떻게 일하는가"},{key:"work_values",label:"직업가치 우선순위",href:"/career/values",storage:"mooa-career-work-values-v1",hint:"무엇을 중요하게 보는가"}] as const;
export function CareerAiPreparation({scope}:{scope:"interest"|"work_style"|"work_values"|"combined"}) {
 const [signedIn,setSignedIn]=useState<boolean|null>(null);
 useEffect(()=>{void(async()=>{try{const {data}=await createClient().auth.getUser();setSignedIn(Boolean(data.user));}catch{setSignedIn(false);}})();},[]);
 const interestRaw=useSyncExternalStore(subscribe,()=>window.sessionStorage.getItem(assessments[0].storage),()=>null); const workStyleRaw=useSyncExternalStore(subscribe,()=>window.sessionStorage.getItem(assessments[1].storage),()=>null); const valuesRaw=useSyncExternalStore(subscribe,()=>window.sessionStorage.getItem(assessments[2].storage),()=>null);
 const complete=useMemo(()=>assessments.filter((_,index)=>Boolean([interestRaw,workStyleRaw,valuesRaw][index])),[interestRaw,workStyleRaw,valuesRaw]); const required=scope==="combined"?assessments:assessments.filter((assessment)=>assessment.key===scope); const missing=required.filter((assessment)=>!complete.some((done)=>done.key===assessment.key)); const combined=scope==="combined";
 if(missing.length)return <AiFrame eyebrow="CAREER AI / CHECKLIST" title={combined?"종합 해설을 위한\n세 가지 관점을 모아주세요.":"해설에 사용할\n검사 결과가 필요해요."} description={combined?"활동 선호, 업무 방식, 중요 조건은 서로 다른 질문입니다. 세 결과가 모이면 한쪽 점수만으로 결론 내리지 않고 연결해 볼 수 있어요.":"먼저 해당 검사를 완료하면, 그 결과를 바탕으로 심층 해설 준비를 이어갈 수 있어요."} status="검사 진행 필요"><section className={styles.todoList}>{missing.map((assessment)=><Link key={assessment.key} href={assessment.href}><span><i>{assessment.key==="interest"?"01":assessment.key==="work_style"?"02":"03"}</i><b>{assessment.label}</b><small>{assessment.hint}</small></span><em>시작하기 <ArrowRight/></em></Link>)}</section><Link className={styles.ghostLink} href="/career">커리어 검사 홈으로</Link></AiFrame>;
 if(signedIn===false)return <AiFrame eyebrow="CAREER AI / PRIVATE" title="해설에 사용할 결과를\n안전하게 확인해 주세요." description="현재 기기에서 완료한 검사 결과는 로그인 뒤에도 이어서 사용할 수 있어요. 해설에 포함할 자료는 직접 선택하게 됩니다." status="로그인 필요"><Link className={styles.primary} href={"/career/login?next=/career/ai?scope="+scope}>로그인 후 해설 준비하기 <ArrowRight/></Link><Link className={styles.ghostLink} href="/career">커리어 검사 홈으로</Link></AiFrame>;
 return <AiFrame eyebrow="MOOA CAREER / AI INSIGHTS" title={combined?"검사 결과를 모아\n더 깊게 읽을 준비를 합니다.":"내 결과를 경험과 연결할\n심층 해설을 준비합니다."} description="AI 심층 해설은 검사 점수를 단정으로 바꾸지 않습니다. 실제 경험과 지원 방향을 함께 검토할 질문으로 정리합니다." status="출시 준비 중"><section className={styles.signalGrid}>{complete.map((assessment)=><article key={assessment.key}><CheckCircle2/><div><b>{assessment.label}</b><span>{assessment.hint}</span></div></article>)}</section><section className={styles.preview}><div className={styles.previewHead}><span><WandSparkles/>AI INSIGHT PREVIEW</span><i>COMING SOON</i></div><div className={styles.previewBody}><div><small>01 / PROFILE SYNTHESIS</small><b>결과 사이의 연결을 읽습니다.</b><p>높은 축을 나열하는 대신, 실제로 몰입할 환경과 확인할 경험을 정리합니다.</p></div><div><small>02 / EXPERIENCE PROMPTS</small><b>경험에서 답을 찾을 질문</b><p>자기소개서에 넣을 문장을 만들지 않고, 먼저 사실을 확인할 질문을 제시합니다.</p></div><div><small>03 / NEXT DIRECTION</small><b>다음 지원을 위한 검토 기준</b><p>지원 공고와 역할에서 무엇을 비교할지 안내합니다.</p></div></div></section><div className={styles.launchNote}><Sparkles/><span><b>AI 심층 해설 출시 준비 중</b><small>실행·결제 흐름이 완성되면 이 화면에서 바로 시작할 수 있어요.</small></span></div><Link className={styles.ghostLink} href="/career/profile">종합 커리어 프로필로</Link></AiFrame>;
}
function AiFrame({eyebrow,title,description,status,children}:{eyebrow:string;title:string;description:string;status:string;children:React.ReactNode}){return <main className={styles.page}><div className={styles.topbar}><Link href="/career">MOOA <b>CAREER</b></Link><span>{status}</span></div><section className={styles.hero}><div className={styles.copy}><p>{eyebrow}</p><h1>{title.split("\n").map((line,index)=><span key={line}>{line}{index===0?<br/>:null}</span>)}</h1><p className={styles.description}>{description}</p></div><div className={styles.orbit} aria-hidden="true"><i/><i/><i/><b><Sparkles/>AI<br/>CAREER</b></div></section><section className={styles.workspace}>{children}</section></main>;}