import Link from "next/link";
import { ArrowRight, BadgeCheck, Clock3, Globe2, LockKeyhole, ShieldCheck } from "lucide-react";
import { careerAssessmentCatalog, type AssessmentAvailability } from "@/domain/career-assessment-catalog";
import styles from "./career-assessment-catalog.module.css";
const statusCopy: Record<AssessmentAvailability, { label: string; detail: string }> = { available: { label: "지금 이용 가능", detail: "간편 결과 제공" }, "license-review": { label: "공개 조건 확인 중", detail: "정식 공개 전" }, "validation-required": { label: "번역·검증 준비", detail: "검증 완료 후 공개" } };
export function CareerAssessmentCatalog({ variant = "page" }: { variant?: "page" | "drawer" }) {
 return <main className={`${styles.catalog} ${variant === "drawer" ? styles.drawer : ""}`}><header className={styles.hero}><span>CAREER ASSESSMENT LIBRARY</span><h1>무엇을 탐색하는지부터<br /><em>명확하게 고릅니다.</em></h1><p>현재 이용 가능한 무아 커리어 탐색 도구와, 원문·번역판으로 준비 중인 도구를 분리해 안내합니다.</p></header><section className={styles.notice}><ShieldCheck /><p><b>결과 사용 범위</b> 모든 결과는 자기이해와 커리어 탐색을 위한 단서입니다. 의료·정신건강 진단, 직업 적합성 또는 채용 결과 판정에 사용하지 않습니다.</p></section><CatalogSection kicker="AVAILABLE NOW" title="바로 해볼 수 있는 검사" items={careerAssessmentCatalog.filter((item) => item.availability === "available")} /><CatalogSection kicker="ENGLISH ORIGINAL TRACK" title="영문 원문 기반 도구" description="영문 원문은 한국어 독자 문항과 같은 검사로 취급하지 않습니다. 각 도구의 재배포 조건과 출처 표기를 점검한 뒤 별도 언어판으로 공개합니다." items={careerAssessmentCatalog.filter((item) => item.language === "en")} /><CatalogSection kicker="KOREAN ADAPTATION TRACK" title="한국어 번역·정식판 후보" description="번역 또는 변경된 외부 도구는 단순 문구 고지만으로 공개하지 않습니다. 라이선스 조건, 변경 사실, 대상 사용자에 대한 검증을 먼저 충족합니다." items={careerAssessmentCatalog.filter((item) => item.availability === "validation-required")} /><section className={styles.footerCard}><Globe2 /><div><b>언어판은 같은 결과로 합산하지 않습니다.</b><p>독자 문항, 영문 원문, 한국어 번역판은 문항·점수·검증 상태가 다르므로 완료 기록과 결과 해석을 분리해 관리합니다.</p></div></section></main>;
}
function CatalogSection({ kicker, title, description, items }: { kicker: string; title: string; description?: string; items: readonly (typeof careerAssessmentCatalog)[number][] }) { return <section className={styles.section}><div className={styles.sectionHead}><div><span>{kicker}</span><h2>{title}</h2></div><b>{String(items.length).padStart(2, "0")}</b></div>{description ? <p className={styles.sectionDescription}>{description}</p> : null}<div className={styles.grid}>{items.map((assessment) => <AssessmentCard key={assessment.id} assessment={assessment} />)}</div></section>; }
function AssessmentCard({ assessment }: { assessment: (typeof careerAssessmentCatalog)[number] }) { const status = statusCopy[assessment.availability]; const content = <><div className={styles.cardTop}><span>{assessment.language.toUpperCase()}</span><small>{assessment.method}</small><b className={styles[assessment.availability]}>{assessment.availability === "available" ? <BadgeCheck /> : <LockKeyhole />}{status.label}</b></div><h3>{assessment.name}</h3><strong>{assessment.formalName}</strong><p>{assessment.purpose}</p><div className={styles.cardFoot}><span><Clock3 />{assessment.meta}</span><em>{status.detail}</em></div><small className={styles.cardNotice}>{assessment.notice}</small></>; return assessment.route ? <Link className={styles.card} href={assessment.route}>{content}<ArrowRight className={styles.arrow} /></Link> : <article className={styles.card} aria-label={assessment.name}>{content}</article>; }