import Link from "next/link";
import { ArrowRight, BadgeCheck, Clock3, Globe2, LockKeyhole, ShieldCheck } from "lucide-react";
import { careerAssessmentCatalog, type AssessmentAvailability } from "@/domain/career-assessment-catalog";
import styles from "./career-assessment-catalog.module.css";
const statusCopy: Record<AssessmentAvailability, { label: string; detail: string }> = { available: { label: "지금 이용 가능", detail: "간편 결과 제공" }, "coming-soon": { label: "결과지 준비 중", detail: "해설 완성 후 공개" }, "license-review": { label: "공개 조건 확인 중", detail: "정식 공개 전" }, "validation-required": { label: "번역·검증 준비", detail: "검증 완료 후 공개" } };
export function CareerAssessmentCatalog({ variant = "page" }: { variant?: "page" | "drawer" }) {
 // In the drawer this is a panel on someone else's page, not the page itself.
 // Rendered as <main><h1> it gave the home two mains and two h1s — and because
 // the drawer is the first child, a crawler read 무엇을 탐색하는지부터 as the
 // home's heading instead of 합격을 위한 준비를 봅니다.
 // variant decides document structure, plus .inPanel for the one thing a 720px
 // panel cannot do (a two-column hero). Deliberately NOT the .drawer class:
 // that block collapses the cards to one column, and the three-column square
 // cards were chosen on purpose.
 const Root = variant === "drawer" ? "section" : "main";
 const Title = variant === "drawer" ? "h2" : "h1";
 const Sub = variant === "drawer" ? "h3" : "h2";
 return <Root className={`${styles.catalog} ${variant === "drawer" ? styles.inPanel : ""}`}><header className={styles.hero}><span>CAREER ASSESSMENT LIBRARY</span><b className={styles.heroKicker}>종합 커리어검사</b><div className={styles.heroRow}><Title className={styles.heroTitle}>무엇을 탐색하는지부터<br /><em>명확하게 고릅니다.</em></Title><p className={styles.heroTerms}>직업심리검사 · 진로검사 · 직업적성검사</p></div></header><section className={styles.notice}><ShieldCheck /><p><b>결과 사용 범위</b> 모든 결과는 자기이해와 커리어 탐색을 위한 단서입니다. 의료·정신건강 진단, 직업 적합성 또는 채용 결과 판정에 사용하지 않습니다.</p></section><CatalogSection kicker="AVAILABLE NOW" title="바로 해볼 수 있는 검사" items={careerAssessmentCatalog.filter((item) => item.availability === "available")} /><CatalogSection kicker="COMING SOON" title="결과지를 다듬고 있는 검사" description="문항과 채점은 끝났지만 결과 화면과 해설이 아직입니다. 설명 없는 점수만 보여드리면 오히려 잘못 읽히기 쉬워, 해설을 마친 뒤 함께 엽니다." items={careerAssessmentCatalog.filter((item) => item.availability === "coming-soon")} /><CatalogSection kicker="ENGLISH ORIGINAL TRACK" title="영문 원문 기반 도구" description="영문 원문은 한국어 독자 문항과 같은 검사로 취급하지 않습니다. 각 도구의 재배포 조건과 출처 표기를 점검한 뒤 별도 언어판으로 공개합니다." items={careerAssessmentCatalog.filter((item) => item.language === "en")} /><CatalogSection kicker="KOREAN ADAPTATION TRACK" title="한국어 번역·정식판 후보" description="번역 또는 변경된 외부 도구는 단순 문구 고지만으로 공개하지 않습니다. 라이선스 조건, 변경 사실, 대상 사용자에 대한 검증을 먼저 충족합니다." items={careerAssessmentCatalog.filter((item) => item.availability === "validation-required")} /><section className={styles.footerCard}><Globe2 /><div><b>언어판은 같은 결과로 합산하지 않습니다.</b><p>독자 문항, 영문 원문, 한국어 번역판은 문항·점수·검증 상태가 다르므로 완료 기록과 결과 해석을 분리해 관리합니다.</p></div></section><section className={styles.seoLead}><p>무료 커리어 검사는 세 가지를 봅니다. <b>무엇을 해보고 싶은지</b>(직업흥미검사), <b>어떤 방식으로 일할 때 편한지</b>(업무성향검사), <b>일에서 무엇을 중요하게 보는지</b>(직업가치관검사)입니다. 직업검사나 진로검사, 취업검사라는 이름으로 찾아오셨다면 대개 이 셋 중 하나가 궁금하셨을 것입니다.</p><p>부르는 이름은 여러 가지입니다. 적성에 무게를 두면 직업적성검사·진로적성검사·직무적성검사라 하고, 성향에 무게를 두면 직업성향검사·커리어성향검사·직무성향검사라 합니다. 커리어진단·진로진단·취업진단, 커리어성향분석·직업성향분석·진로성향분석, 커리어테스트·진로테스트·직업테스트도 대체로 같은 것을 가리킵니다. 무아에서는 세 결과가 하나의 커리어프로파일로 모여 진로탐색·직업탐색·커리어탐색의 출발점이 됩니다.</p><p><b>다만 표준화된 직업심리검사나 진로심리검사는 아닙니다.</b> 임상 진단이나 채용 판정에 쓰지 않고, 직업을 대신 골라주지도 않습니다. 직업가치검사나 커리어적성검사, 직업프로파일을 찾으셨다면 정식 검사를 대신하는 도구가 아니라, <b>지원서를 쓰기 전에 내 기준을 정리하는 단계</b>로 보시는 편이 맞습니다.</p></section></Root>;
}
function CatalogSection({ kicker, title, description, items }: { kicker: string; title: string; description?: string; items: readonly (typeof careerAssessmentCatalog)[number][] }) { return <section className={styles.section}><div className={styles.sectionHead}><div><span>{kicker}</span><h2>{title}</h2></div><b>{String(items.length).padStart(2, "0")}</b></div>{description ? <p className={styles.sectionDescription}>{description}</p> : null}<div className={styles.grid}>{items.map((assessment) => <AssessmentCard key={assessment.id} assessment={assessment} />)}</div></section>; }
function AssessmentCard({ assessment }: { assessment: (typeof careerAssessmentCatalog)[number] }) { const status = statusCopy[assessment.availability]; const content = <><div className={styles.cardTop}><span>{assessment.language.toUpperCase()}</span><small>{assessment.method}</small><b className={styles[assessment.availability]}>{assessment.availability === "available" ? <BadgeCheck /> : <LockKeyhole />}{status.label}</b></div><h3>{assessment.name}</h3><strong>{assessment.formalName}</strong><p>{assessment.purpose}</p><div className={styles.cardFoot}><span><Clock3 />{assessment.meta}</span><em>{status.detail}</em></div><small className={styles.cardNotice}>{assessment.notice}</small></>; return assessment.route ? <Link className={styles.card} href={assessment.route}>{content}<ArrowRight className={styles.arrow} /></Link> : <article className={styles.card} aria-label={assessment.name}>{content}</article>; }