-- `document_kind`에 "지원자가 직접 알려준 사실"을 더합니다.
--
-- 간편 입력의 "더 정확하게 써드릴게요 · 서류에 없는 사실" 칸이 만드는 문서입니다.
-- 지금까지는 `OTHER`로 저장됐고, `OTHER`는 모델에게 **'portfolio'** 라는 이름으로
-- 전달되며 참고자료 예산에서 **맨 뒤**에 섭니다. 지원자가 "이건 서류에 없어서
-- 따로 적는다"고 넣어 준 사실이 작품집으로 소개되고, 자료를 많이 낸 사람일수록
-- 먼저 잘렸습니다. `CERTIFICATE`가 겪었던 것과 같은 문제입니다.
--
-- 트랜잭션으로 감싸지 않습니다. `alter type ... add value`는 같은 트랜잭션 안에서
-- 그 값을 다시 쓸 수 없고, 뒤따르는 마이그레이션이 바로 그 값을 씁니다.
--
-- `if not exists`라 여러 번 실행해도 안전합니다.
alter type public.document_kind add value if not exists 'APPLICANT_NOTE';
